<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>promise</title>
</head>
<body>
    <script>
        // Promise 是异步编程的一种解决方案
        // 所谓Promise，简单说就是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作）的结果
        // 从语法上说，Promise 是一个对象，从它可以获取异步操作的消息
        // (1) 对象的状态不受外界影响
        // 有三种状态：Pending（进行中）、Resolved（已完成，又称 Fulfilled）和Rejected（已失败）
        // 只有异步操作的结果，可以决定当前是哪一种状态，任何其他操作都无法改变这个状态
        // (2) 一旦状态改变，就不会再变，任何时候都可以得到这个结果
        // Promise对象的状态改变，只有两种可能：从Pending变为Resolved和从Pending变为Rejected
        // Promise也有一些缺点
        // 1. 无法取消Promise，一旦新建它就会立即执行，无法中途取消
        // 2. 如果不设置回调函数，Promise内部抛出的错误，不会反应到外部
        // 3. 当处于Pending状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）


        // ES6规定，Promise对象是一个构造函数，用来生成Promise实例
        // Promise构造函数接受一个函数作为参数
        // 该函数的两个参数分别是resolve和reject
        // 它们是两个函数，由JavaScript引擎提供，不用自己部署
        /*var promise = new Promise(function(resolve, reject) {
            // ... some code

            if (/!* 异步操作成功 *!/){
                resolve(value);
            } else {
                reject(error);
            }
        });*/
        // resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”（即从Pending变为Resolved）
        // 在异步操作成功时调用，并将异步操作的结果，作为参数传递出去
        // reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”（即从Pending变为Rejected）
        // 在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去
        // Promise实例生成以后，可以用then方法分别指定Resolved状态和Reject状态的回调函数
        /*promise.then(function(value) {
            // success
        }, function(error) {
            // failure
        });*/
        // then方法可以接受两个回调函数作为参数
        // 第一个回调函数是Promise对象的状态变为Resolved时调用
        // 第二个回调函数是Promise对象的状态变为Reject时调用（可选）
        // 这两个函数都接受Promise对象传出的值作为参数
        function timeout(ms) {
            return new Promise((resolve, reject) => {
                setTimeout(resolve, ms, 'done');
            });
        }
        timeout(1000).then( value => console.log(value) );

        // Promise新建后就会立即执行
        let promise = new Promise(function(resolve, reject) {
            console.log('Promise');
            resolve();
        });

        promise.then(function() {
            console.log('Resolved.');
        });

        console.log('Hi!');

        // 异步加载图片的例子
        function loadImageAsync(url) {
            return new Promise(function(resolve, reject) {
                var image = new Image();

                image.onload = function() {
                    resolve(image);
                };

                image.onerror = function() {
                    reject(new Error('Could not load image at ' + url));
                };

                image.src = url;
            });
        }

        // then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）
        // 因此可以采用链式写法，即then方法后面再调用另一个then方法


        // Promise.prototype.catch方法是.then(null, rejection)的别名，用于指定发生错误时的回调函数
        // 如果异步操作抛出错误，状态就会变为Rejected，就会调用catch方法指定的回调函数，处理这个错误
        // 另外，then方法指定的回调函数，如果运行中抛出错误，也会被catch方法捕获
        getJSON('/posts.json').then(function(posts) {
            // ...
        }).catch(function(error) {
            // 处理 getJSON 和 前一个回调函数运行时发生的错误
            console.log('发生错误！', error);
        });
        // 如果Promise状态已经变成Resolved，再抛出错误是无效的
        // Promise 对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止
        // 也就是说，错误总是会被下一个catch语句捕获
        getJSON('/post/1.json').then(function(post) {
            return getJSON(post.commentURL);
        }).then(function(comments) {
            // some code
        }).catch(function(error) {
            // 处理前面三个Promise产生的错误
        });
        // 一共有三个Promise对象：一个由getJSON产生，两个由then产生
        // 它们之中任何一个抛出的错误，都会被最后一个catch捕获


        // 一般来说，不要在then方法里面定义Reject状态的回调函数（即then的第二个参数），总是使用catch方法
        // 如果没有使用catch方法指定错误处理的回调函数
        // Promise对象抛出的错误不会传递到外层代码，即不会有任何反应


        // catch方法返回的还是一个 Promise 对象，因此后面还可以接着调用then方法
        var someAsyncThing = function() {
            return new Promise(function(resolve, reject) {
                // 下面一行会报错，因为x没有声明
                resolve(x + 2);
            });
        };

        someAsyncThing()
            .catch(function(error) {
                console.log('oh no', error);
            })
            .then(function() {
                console.log('carry on');
            });


        // Promise.all方法用于将多个Promise实例，包装成一个新的Promise实例
        // Promise.all方法的参数可以不是数组，但必须具有Iterator接口，且返回的每个成员都是Promise实例
        // 如果不是，就会先调用Promise.resolve方法，将参数转为Promise实例，再进一步处理
        // var p = Promise.all([p1, p2, p3]);
        // p的状态由p1、p2、p3决定，分成两种情况
        // 1. 只有p1、p2、p3的状态都变成fulfilled，p的状态才会变成fulfilled
        // 此时p1、p2、p3的返回值组成一个数组，传递给p的回调函数
        // 2. 只要p1、p2、p3之中有一个被rejected，p的状态就变成rejected
        // 此时第一个被reject的实例的返回值，会传递给p的回调函数
        /*var promises = [2, 3, 5, 7, 11, 13].map(function (id) {
            return getJSON("/post/" + id + ".json");
        });

        Promise.all(promises).then(function (posts) {
            // ...
        }).catch(function(reason){
            // ...
        });*/


        // Promise.race方法同样是将多个Promise实例，包装成一个新的Promise实例
        // var p = Promise.race([p1, p2, p3]);
        // 只要p1、p2、p3之中有一个实例率先改变状态，p的状态就跟着改变
        // 那个率先改变的 Promise 实例的返回值，就传递给p的回调函数


        // Promise.resolve 将现有对象转为Promise对象
        /*Promise.resolve('foo')  ==> new Promise(resolve => resolve('foo'))*/
    </script>
</body>
</html>